### ISSUE TITLE
Deploy Shiny server on a VPS

### ISSUE THREAD

**Issue by alwil** [UD3-Lab/mintEMU#108]
- [x] read the [Shiny server deployment documentation](https://posit.co/products/open-source/shinyserver/)
- [x] request the VPS from the Service Desk 
- [x] configure the VPS according to the instructions 
- [x] test if the mintEMU Shiny works on the server

**Comment by alwil** [comment]
Hi @cforgaci,

Could you request the VPS at the [Top desk service](https://tudelft.topdesk.net/tas/public/ssp/content/serviceflow?unid=418c986f186d4934848dc2712039ed34) with the following configuration ( please feel free to adapt the name of the application and the qualified domain): 

![image](https://github.com/UD3-Lab/mintEMU/assets/7210572/8372d886-d1b7-4fc9-b9f0-6907d6a35086)

![image](https://github.com/UD3-Lab/mintEMU/assets/7210572/737cc273-ed10-4a7d-8bd4-f97ee26835af)

Here are the [DCC guides on requesting the VPS](https://tu-delft-dcc.github.io/infrastructure/VPS_request.html)
Here's the administrator's guide to [Shiny Server configuration](https://docs.posit.co/shiny-server/)

**Comment by alwil** [comment]
Steps taken please note that step 2) diverges from the [installation instructions](https://posit.co/download/shiny-server/) : 

1)  `sudo apt-get install r-base`
2) `sudo su
R -e "install.packages('shiny', repos='https://cran.rstudio.com/')"
exit`

**Comment by alwil** [comment]
Instructions to deploy Shiny app  in the server: https://www.linode.com/docs/guides/how-to-deploy-rshiny-server-on-ubuntu-and-debian/

**Comment by cforgaci** [comment]
@alwil, the Shiny server is up and running at http://mintemu_shiny.bk.tudelft.nl:3838/

**Comment by alwil** [comment]
[Shiny Server Quickstart documentation](https://docs.posit.co/shiny-server/#quick-start)

**Comment by alwil** [comment]
I had some problems with installing `devtools`. I've managed to find workarounds, but it led to some conflicts and eventually plots not showing even in the Shiny examples. It had to do with some conflict in the `ragg` package that has been installed but not recognized by shiny server. 
I ended up removing all the libraries and reinstalling R.

**Comment by alwil** [comment]
I've ended up installing `devtools` the following way, based on [stackoverflow suggestions](https://stackoverflow.com/questions/74821945/cannot-install-r-packages-on-new-ubuntu-device):

```sudo apt-get install r-cran-devtools```

**Comment by alwil** [comment]
the app is running, but crashes instantly, as the package data is not available. I tired to move the data manually, but it's not trivial in the package context. 
The two ways to go about it are 
1) reinstall the mintEMU package on the server once the datasets are added to the github repository
2) created a 'static' version of the app, that includes datasets in its folder and adapt the script slightly.

**Comment by alwil** [comment]
The app is up and running in it's 'static version'. it can be accessed through: http://mintemu_shiny.bk.tudelft.nl:3838/mintemu/

On the server side, it is located in `/srv/shiny-server/mintemu/`. 
The code from the `mintEMU` package app is copied from the `app_ui.R` and `app_server.R` scripts to the `ui.R` and `server.R` files, respectively. This means that whenever there is an update in the package Shiny app, the changes would need to be copied manually to those scripts. Similarly, the `emu_clean.rda` and `emu_metadata.rda` data sets have been manually added to the `data` folder and would need to be updated when there's any change. 

In the long run, i.e. once there's a stable version of a dataset that is stored as a part of the package, the `mintEMU` package should be reinstalled with the following code:

 ```
sudo su
R -e "devtools::install_github('UD3-Lab/mintEMU')"
exit
```

Then the package folder needs to be identified in the server. it can be done with the command:

 ```
sudo su
R -e "system.file('mintEMUapp', package = 'mintEMU')"
exit
```
Finally, it needs to be copied to the `/srv/shiny-server/` directory:

``` 
sudo cp -R <mintEMUapp directory> /srv/shiny-server/

```
