### ISSUE TITLE
Shiny testing

### ISSUE THREAD

**Issue by alwil** [UD3-Lab/mintEMU#113]
- [ Shiny testing overview - POSIT](https://shiny.posit.co/r/articles/improve/testing-overview/)
 - [`shinytest` package](https://rstudio.github.io/shinytest/)
 - [`shinyloadtest` package](https://rstudio.github.io/shinyloadtest/?_gl=1*mbji7u*_ga*NjU0NjYwMTIzLjE2ODQ3NjM3NjE.*_ga_8QJS108GF1*MTY4OTA3NjcwNS4yLjAuMTY4OTA3N)

**Comment by cforgaci** [comment]
Copied to resources repo
