### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by Selkubi** [UD3-Lab/mintEMU#136]
When looking through the app, the data point in Spain doesn't produce the word cloud. Upon inspecting, I've noticed that the data is not correctly translated from pdf 

To check I run the following:

```
emu_metadata[emu_metadata$title=="Landing on the coast",]
head_text(emu_clean$text_clean[43])
```

Maybe it would be useful to remove this data point entirely from the dataset.

**Comment by cforgaci** [comment]
We do not have this problem anymore as the author did not respond to the permission request and thus it was excluded with #118

**Comment by cforgaci** [comment]
I will close this issue now and only reopen it and deal with this issue if the author gives permission.
