### ISSUE TITLE
Configure SSH tunneling for easy shiny server access

### ISSUE THREAD

**Issue by alwil** [UD3-Lab/mintEMU#141]
- follow the [DCC guides](https://tu-delft-dcc.github.io/infrastructure/VPS_SSH.html). You can use different  algorithm for generating the ssh key, e.g. `ssh-keygen -f ~/.ssh/<my-keyname> -t ed25519`

- then check the guides for [copying files to the server](https://tu-delft-dcc.github.io/infrastructure/moving_data.html)

- Just FYI, if you ever have lots of data that you need the shiny-server to interact with, you might want to [request a project drive](https://tu-delft-dcc.github.io/data/project_drive_request.html) and [mount it on the server](https://tu-delft-dcc.github.io/data/project_drive_mounting.html)

**Comment by cforgaci** [comment]
I followed the steps in the documentation, but I still do not have access permission from bastion to the mintemu server.

**Comment by alwil** [comment]
@cforgaci , you can try adding the following line to the `.ssh/config` file on your local machine: `IdentityFile ~/.ssh/<key_to_be_used>`

Here's how it look like for me now ( I named the ssh key `mint`):

```
Host mintemu
        HostName mintemu_shiny.bk.tudelft.nl
        User awilczynski
        ProxyCommand ssh bastion -W %h:%p
        IdentityFile ~/.ssh/mint
```

It worked like a charm for me!

**Comment by cforgaci** [comment]
note that copying works only to ~ on the server, then copy from there to the target directory

**Comment by cforgaci** [comment]
Issue solved. Closing.
