### ISSUE TITLE
Project management on GitHub

### ISSUE THREAD

**Issue by alwil** [UD3-Lab/mintEMU#21]
- [Code Refinery lesson on centralized workflow](https://coderefinery.github.io/git-collaborative/centralized/)
- [Pull requests - GitHub documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
- [Simple Sprint Planning using GitHub tools](https://www.youtube.com/watch?v=eit4s9hRwfA)
- [Sprint Planning and Management using Task Boards in GitHub](https://www.youtube.com/watch?v=-MBEnpAgmug)

**Comment by alwil** [comment]
@cforgaci, in case you don't have this alias configured, it's a useful tool to investigate git history ;

```
git config --global alias.graph "log --all --graph --decorate --oneline"

```

Once you have it set up you can call it (with `git graph` command) instead of `git log --oneline`

**Comment by cforgaci** [comment]
Added to resources repo
