### ISSUE TITLE
Project workflow improvements

### ISSUE THREAD

**Issue by alwil** [UD3-Lab/mintEMU#22]
- [Reproducible Data Analytic Workflows for Economics ](https://lachlandeer.github.io/snakemake-econ-r-tutorial/)
- [Using `reticulate` in R package](https://rstudio.github.io/reticulate/articles/package.html)
- [Building reproducible analytical pipelines with R](https://raps-with-r.dev/) - This is an excellent book written by [Bruno Rodrigues](https://twitter.com/brodriguesco) a practicing data scientist who is an advocate of software engineering in the field of data science. The book provides an in-depth overview of the tools, practices and techniques for reproducible analytical pipelines (RAPs). The book does not teach R programming basics, nor does it cover statistics and visualisation. The language is accessible and non-academic, with multiple references to the pains encounters by data science practitioners due to the lack of reproducibility.

**Comment by cforgaci** [comment]
Added to resources repo
