### ISSUE TITLE
Rules to adapt stop words list

### ISSUE THREAD

**Issue by alwil** [UD3-Lab/mintEMU#26]
- [ ] interactive interface for user to select the stopwords
- [ ] statistics / visualisations of common & suspicious words
 
Rules to create:
- [x] #56
   - [x]  crossreference with topic
- [ ] Identify popular words, evenly spread throughout all/many publications but not conveying any meaning - additional stop words. Consider words:
   - [ ] with non-letters
   - [ ] short words (e.g. 4 characters and less)
- [ ] Lemmatize words with `textstem::lemmatize_words()` . Check if successful by:
   - [ ] comparing top words lists before and after lemmatization
   - [ ] extracting random sample of words and comparing those.

**Comment by cforgaci** [comment]
@alwil can you please share the data you used for [RCafe-text-reader](https://github.com/Delft-RCafe/RCafe-text-reader)? I'd like to run the Rmd to see what can be reused/adapted. Thanks!

**Comment by alwil** [comment]
@cforgaci , I have added the data (`text_data.RDS`) to `data/examples/RCafe-text-reader` in our Surf Drive. 
Please let me know if you can't access it.
