### ISSUE TITLE
R packaging

### ISSUE THREAD

**Issue by alwil** [UD3-Lab/mintEMU#27]
## Testing 

- [ Carpentry lesson](https://carpentries-incubator.github.io/lesson-R-packaging/06-testing/index.html)

## Managing dependencies

- [Carpentry lesson](https://carpentries-incubator.github.io/lesson-R-packaging/07-dependencies/index.html)

## Versioning 

- See [the carpentry course on R Packaging](https://carpentries-incubator.github.io/lesson-R-packaging/04-functions/index.html#more-on-description) for info about versioning.

> The Version field helps you and your users keep track of the package version. It is advisable to use semantic versioning. In a nutshell, semantic versioning means using a MAJOR.MINOR.PATCH structure for naming your versions. If your new version only fixes some bugs, increase the PATCH by one. If your new version includes new features, increase the MINOR by one. If your new version includes new features that are not backwards compatible, increase MAJOR by one.

## Documentation

- [Carpentry Lesson](https://carpentries-incubator.github.io/lesson-R-packaging/07-documentation/index.html)

**Comment by cforgaci** [comment]
Added to resources repo
