### ISSUE TITLE
How to keep information about PDF structure in extracted text?

### ISSUE THREAD

**Issue by cforgaci** [UD3-Lab/mintEMU#57]
When we extract and clean the text from the PDFs, we are losing valuable information. It would be great if we could get at least some of these structural elements from the original PDF:
- [x] get the page numbers for each paragraph
- [ ] extract the thesis structure from the table of contents (e.g., to remove sections, such as Acknowledgement, that lack valuable content)
- [ ] extract the location of figures, at least the page on which they are located
- [ ] identify what is a caption

**Comment by alwil** [comment]
to be done by Sprint 4

**Comment by alwil** [comment]
For TOC search:
- see how many hits will Document.get_toc() yield
- find words 'contents' in each files ; look for page number; neighbouring words;  text until the next chapter defining words (e.g. acknowledgements, chapter)
- retrieve the content of everything between
-

**Comment by alwil** [comment]
- no TOC retrieval
- check with Manuel if the caption for pictures extracted in their project
