### ISSUE TITLE
Topic modelling visualisation

### ISSUE THREAD

**Issue by alwil** [UD3-Lab/mintEMU#77]
- [Topic modelling with R](https://knowledger.rbind.io/post/topic-modeling-using-r/)
- [LDAvis package](https://github.com/cpsievert/LDAvis)
- [A Link Between topicmodels LDA and LDAvis](https://www.r-bloggers.com/2015/05/a-link-between-topicmodels-lda-and-ldavis/)
- [https://www.r-bloggers.com/2021/07/visualizing-topic-models-with-crosstalk/](https://www.r-bloggers.com/2021/07/visualizing-topic-models-with-crosstalk/)
- [topic models](https://medium.com/broadhorizon-cmotions/nlp-with-r-part-1-topic-modeling-to-identify-topics-in-restaurant-reviews-3ee870e6cd8)

**Comment by cforgaci** [comment]
https://towardsdatascience.com/latent-dirichlet-allocation-intuition-math-implementation-and-visualisation-63ccb616e094
