### ISSUE TITLE
Finalize data preparation

### ISSUE THREAD

**Issue by alwil** [UD3-Lab/mintEMU#83]
- [x] Set a deadline for permissions - **31 August 2023**
- [ ]  #79 
- [ ]  After the deadline passes: 
  - [ ]   filter the theses for which permission has been given ( use the metadata field `permission_granted == TRUE `  ) in the `analysis/supplementary-materials/merge-metadata-files.R`
  - [x]    move the part converting the theses from pdf to text from `paper.qmd`  to `data-raw` and saving to `emu_text_raw.csv` to `inst/extdata/` folder.
  - [x] #93
  - [ ] #105
  - [x]   write a single script in the `data-raw` folder to clean the data and save it in the package
    - [x]     the starting point of the script will be the 4TU published data URL 
    - [x]      the script will clean the dataset and save it  as `emu_text_df.rda` ( with the `usethis::use_data()` )
    - [x]     in the paper, we describe conversion step and the cleaning procedure, pointing to data-raw folder, but removing any code chunks duplicating the procedure
    - [x] #104

**Comment by cforgaci** [comment]
We move the deadline for permission to the end of the summer.
